[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FCCQuadrature = "7e58c0cd-f370-453c-9274-eb333b7aace6"
QEDfields = "ac3a6c97-e859-4b9f-96bb-63d2a216042c"

[sources]
QEDfields = {path = "/Users/uwe/Work/jlProjects/QEDjl-project/forks/QEDfields.jl"}
